export const ACTION_SET_SYMBOL = "SET_SYMBOL";
export const ACTION_LOAD_PROFILE = "LOAD_PROFILE";
export const ACTION_SHOW_PROFILE = "SHOW_PROFILE";
export const ACTION_SET_INFO = "SET_INFO";
export const ACTION_SET_PRICE = "SET_PRICE";
